TARGET1=visualSSS.c
TARGET2=share.c retrive.c header_parser.c
INCLUDES= .
TARGET3=visualSSS
CC=gcc
CFLAGS=
$(TARGET3): $(TARGET1) $(TARGET2)
	$(CC) -I $(INCLUDES) $(CFLAGS) -o	$(TARGET3) $(TARGET1) $(TARGET2)
